### PR TITLE
Added zombie movement and attack

### PR DESCRIPTION
**Pull request by MonsieurDuck**
- zombie moves up or down until it hits obstacle and then changes direction
- zombie follows soul when its close
- zombie attacks soul when its within melee range
- soul and zombie now die along with an opacity animation when its hurt
- zombie layer does not collide with soul layer, but does with trigger layer

### CODE REVIEW

**Review by NickSoultanian — APPROVED** [review]

**Review by engineereng — COMMENTED** [review]
I found a couple cases where the zombies get stuck after killing a ghost, and one case where an error is thrown:




https://user-images.githubusercontent.com/38707101/211178376-d01e2950-fe90-4c2b-8852-c0aa62d66376.mp4

**Comment by MonsieurDuck** [comment]
working on fixing bugs now

**Comment by MonsieurDuck** [comment]
Should be fixed now @engineereng

**Review by brayshi — APPROVED** [review]
Lgtm

**Review by engineereng — APPROVED** [review]
Just tested. Great work!

**Pull request merged**
