### PR TITLE
Context steering ai integration

### PR DESCRIPTION
**Pull request by brayshi**
Completed Soul path finding to avoid obstacles such as walls and borders. 
Code is present in the AI folder.

AI Data: Stores this entity's information to be passed to other components
Detectors: Detect if objects in specified layer is present. If true, stores objects in AI Data
SteeringBehaviours: Using the collision objects present in AI Data, vector distances are calculated to determine dangers and interests within AI's given radius.
The steering behaviour can then be used by AI's movement system to guide it out of places like corners when necessary

Also added IsSoul and SoulFire to check if an object is a soul. if it is, soul fire objects on the map instantly destroy the soul when put in contact

https://user-images.githubusercontent.com/83468661/211181963-5774a590-f2f2-4784-b05d-05e75eb3ff3c.mp4

### CODE REVIEW

**Comment by engineereng** [comment]
Could you remove the UserSettings folder from your branch, and could you remove your changes to RIPLevels.unity?

As we discussed in call, it might be easier to save your revised sheep into the sheep prefab we have.

**Review by engineereng — CHANGES_REQUESTED** [review]
Could you remove the UserSettings folder from your branch, and could you remove your changes to RIPLevels.unity?

As we discussed in call, it might be easier to save your revised sheep into the sheep prefab we have.

**Review by engineereng — APPROVED** [review]
LGTM!

**Review by NickSoultanian — APPROVED** [review]

**Review by MonsieurDuck — APPROVED** [review]
good stuff

**Pull request merged**
