### PR TITLE
adjusted player hitbox and fixed zombie double attack bug

### PR DESCRIPTION
**Pull request by MonsieurDuck**
- zombie now attacks ghost correct amount of times
- death now brings hurtable object to death layer and death tag, makes sprite invisible, and then destroys the object 4 seconds later

### CODE REVIEW

**Comment by engineereng** [comment]
@MonsieurDuck I tested two things: the hitbox and the zombie behavior.

## Hit box
The new hitbox for the player works a lot better than before! I think the rounded corners and thinner sides make hitting side walls feel a lot better. Hitting a wall at the bottom works well, too. (0:00 to 0:22 in the video).

While testing, I noticed that the top box sprite seems to be misaligned with the hitbox now (happens around 0:25)

https://user-images.githubusercontent.com/38707101/211211620-29407e61-cf00-4a06-b578-1c6054a5bd68.mp4


This might be an animator thing, though? (cc @NickSoultanian)
image

## Zombie behavior, ghost dying
The ghost is pronounced dead when the zombie attacks it, which works well.

However, I think the **entity** should be disabled, not the **sprite**. Otherwise, it just turns invisible and can still move. It's possible for a zombie to keep attacking a ghost while "dead" (0:20 in the video)

https://user-images.githubusercontent.com/38707101/211211938-2c217dfb-533e-4048-ba1e-77979abea4b8.mp4

**Comment by engineereng** [comment]
@MonsieurDuck Something that works for me is (starting on line 27 in `Hurtable.cs`):

```diff
private IEnumerator HurtCoroutine(){
        sprite.color = new Color(1.0f, 1.0f, 1.0f, 0.7f);
        if (health <= 0) {
            hurtableObject.tag = "Dead";
            hurtableObject.layer = deadLayer;
            yield return new WaitForSeconds(0.3f);
-          sprite.enabled=false
-          yield return new WaitForSeconds(6.0);
           Die();
        }
        yield return new WaitForSeconds(0.3f);
        sprite.color = defaultColor;
    }

    private void Die()
    {
        Debug.Log("Dead!");
-        Destroy(hurtableObject);
-        
-        // TODO 
-        // play some death animation
-        // disable the entity
+        Destroy(hurtableObject, 6.0f); // destroy the object after 6 seconds
+       hurtableObject.SetActive(false); // disable the object
    }
```

I'm not exactly sure if the "Dead" tag does anything, either.

**Review by engineereng — CHANGES_REQUESTED** [review]
See above comments

**Review by NickSoultanian — DISMISSED** [review]

**Review by brayshi — COMMENTED** [review]
Are the changes in the scenes and UserSettings needed in this merge request?

**Comment by MonsieurDuck** [comment]
> @MonsieurDuck Something that works for me is (starting on line 27 in `Hurtable.cs`):
> 
> ```diff
> private IEnumerator HurtCoroutine(){
>         sprite.color = new Color(1.0f, 1.0f, 1.0f, 0.7f);
>         if (health <= 0) {
>             hurtableObject.tag = "Dead";
>             hurtableObject.layer = deadLayer;
>             yield return new WaitForSeconds(0.3f);
> -          sprite.enabled=false
> -          yield return new WaitForSeconds(6.0);
>            Die();
>         }
>         yield return new WaitForSeconds(0.3f);
>         sprite.color = defaultColor;
>     }
> 
>     private void Die()
>     {
>         Debug.Log("Dead!");
> -        Destroy(hurtableObject);
> -        
> -        // TODO 
> -        // play some death animation
> -        // disable the entity
> +        Destroy(hurtableObject, 6.0f); // destroy the object after 6 seconds
> +       hurtableObject.SetActive(false); // disable the object
>     }
> ```
> 
> I'm not exactly sure if the "Dead" tag does anything, either.

The "Dead" tag is relevant because the zombie checks for the "Soul" tag in it's attack, so once it's pronounced dead it shouldnt be attacking the soul. However like you said, it still attacks when the sprite is invisible and that is because I realized that the children of the soul (collider, etc.) still have the "Soul" tag so it starts a collision but then doesn't attack since the hurtable script isnt attached to the children.

The problem with setting the entity inactive before the 6-second wait is that the loop is still going in the zombie script, so it tries to reference a deactivated entity which gives an error. Destroy and deactivate are similar in that they don't allow you to reference the object anymore. However with some of my recent changes the timing should be less of a problem, so I'll change it to your code. 

I'll make a change so that the children are also undetected by the zombie once they die and then I'll push again. 

In reference to the hitbox, I think that the "up" animation sprite is just slightly moved over, and I think we should fix that if we have time after most of the game is done as it doesn't seem to be hurting anything, especially since the reaper doesn't have a  hitbox and it's only used as a collider. Otherwise we can just slightly increase the box so it looks a bit better.

**Comment by MonsieurDuck** [comment]
> Are the changes in the scenes and UserSettings needed in this merge request?

You're right, I don't think they're needed. I'll remove it in the next push.

**Comment by MonsieurDuck** [comment]
@engineereng also i think you may have accidentally attached the same video twice

**Review by engineereng — APPROVED** [review]
Works for me!

**Pull request merged**
